In [20]:
import numpy as np
from numpy import genfromtxt

In [21]:
#my data
my_data = genfromtxt('Q1_LEO_TSANG.csv', delimiter=',')

In [22]:
reference = genfromtxt('reference_data2.csv', delimiter=',')

In [23]:
reference

array([[1., 7., 3., ..., 3., 4., 1.],
       [3., 8., 6., ..., 1., 5., 4.],
       [1., 1., 4., ..., 9., 4., 5.],
       ...,
       [4., 9., 5., ..., 6., 5., 8.],
       [5., 9., 6., ..., 7., 4., 5.],
       [8., 5., 6., ..., 5., 0., 7.]])

In [24]:
reference[0]

array([1., 7., 3., 2., 9., 0., 9., 5., 7., 5., 7., 2., 1., 9., 3., 2., 7.,
       3., 4., 1.])

In [25]:
test = np.array([[6., 0., 1., 2., 8., 5., 9., 0., 1., 6., 6., 2., 2., 0., 1., 8.,
        7., 1., 2., 9.],
       [8., 8., 8., 3., 8., 0., 9., 5., 4., 1., 8., 9., 9., 0., 9., 4.,
        3., 9., 1., 1.],
       [3., 4., 4., 5., 9., 5., 6., 3., 2., 2., 6., 9., 7., 7., 4., 0.,
        3., 6., 9., 0.],
       [2., 0., 4., 2., 7., 9., 8., 1., 3., 7., 3., 8., 7., 7., 1., 1.,
        4., 5., 8., 6.],
       [6., 5., 7., 8., 6., 0., 7., 7., 4., 3., 8., 5., 2., 7., 9., 6.,
        9., 7., 9., 8.],
       [2., 9., 3., 3., 2., 4., 7., 3., 7., 7., 4., 8., 1., 6., 9., 0.,
        2., 9., 5., 6.],
       [8., 4., 0., 5., 0., 5., 1., 8., 0., 4., 7., 3., 7., 1., 5., 7.,
        3., 0., 9., 2.],
       [9., 8., 3., 0., 2., 2., 6., 1., 4., 5., 1., 0., 1., 2., 2., 5.,
        7., 3., 0., 7.],
       [9., 4., 1., 9., 0., 8., 8., 2., 1., 1., 0., 3., 8., 7., 7., 2.,
        5., 1., 0., 3.],
       [5., 2., 2., 8., 9., 1., 3., 9., 5., 9., 0., 5., 6., 7., 9., 3.,
        0., 8., 1., 6.],[1., 7., 3., 2., 9., 0., 9., 5., 7., 5., 7., 2., 1., 9., 3., 2., 7.,
       3., 4., 1.]])

In [26]:
test

array([[6., 0., 1., 2., 8., 5., 9., 0., 1., 6., 6., 2., 2., 0., 1., 8.,
        7., 1., 2., 9.],
       [8., 8., 8., 3., 8., 0., 9., 5., 4., 1., 8., 9., 9., 0., 9., 4.,
        3., 9., 1., 1.],
       [3., 4., 4., 5., 9., 5., 6., 3., 2., 2., 6., 9., 7., 7., 4., 0.,
        3., 6., 9., 0.],
       [2., 0., 4., 2., 7., 9., 8., 1., 3., 7., 3., 8., 7., 7., 1., 1.,
        4., 5., 8., 6.],
       [6., 5., 7., 8., 6., 0., 7., 7., 4., 3., 8., 5., 2., 7., 9., 6.,
        9., 7., 9., 8.],
       [2., 9., 3., 3., 2., 4., 7., 3., 7., 7., 4., 8., 1., 6., 9., 0.,
        2., 9., 5., 6.],
       [8., 4., 0., 5., 0., 5., 1., 8., 0., 4., 7., 3., 7., 1., 5., 7.,
        3., 0., 9., 2.],
       [9., 8., 3., 0., 2., 2., 6., 1., 4., 5., 1., 0., 1., 2., 2., 5.,
        7., 3., 0., 7.],
       [9., 4., 1., 9., 0., 8., 8., 2., 1., 1., 0., 3., 8., 7., 7., 2.,
        5., 1., 0., 3.],
       [5., 2., 2., 8., 9., 1., 3., 9., 5., 9., 0., 5., 6., 7., 9., 3.,
        0., 8., 1., 6.],
       [1., 7., 3., 2., 9., 0.

In [31]:
my_data.shape

(1000000, 20)

In [35]:
my_data.tolist().index([1., 7., 3., 2., 9., 0., 9., 5., 7., 5., 7., 2., 1., 9., 3., 2.,
        7., 3., 4., 1.])

ValueError: [1.0, 7.0, 3.0, 2.0, 9.0, 0.0, 9.0, 5.0, 7.0, 5.0, 7.0, 2.0, 1.0, 9.0, 3.0, 2.0, 7.0, 3.0, 4.0, 1.0] is not in list

In [39]:
my_data.tolist().index(list(reference[0]))

ValueError: [1.0, 7.0, 3.0, 2.0, 9.0, 0.0, 9.0, 5.0, 7.0, 5.0, 7.0, 2.0, 1.0, 9.0, 3.0, 2.0, 7.0, 3.0, 4.0, 1.0] is not in list

In [41]:
my_data[0]

array([6., 0., 1., 2., 8., 5., 9., 0., 1., 6., 6., 2., 2., 0., 1., 8., 7.,
       1., 2., 9.])

In [44]:
my_data2 = np.append(my_data,reference, axis = 0)

In [45]:
len(my_data2)

1001000

In [47]:
my_data2[1000000]

array([1., 7., 3., 2., 9., 0., 9., 5., 7., 5., 7., 2., 1., 9., 3., 2., 7.,
       3., 4., 1.])

In [48]:
my_data2.tolist().index(list(reference[0]))

1000000