In [1]:
import numpy as np

In [3]:
S= np.random.randint(0,10,size=([10000,20]), dtype='int32')

In [4]:
reference = S[np.random.choice(len(S),10,replace=True)]

In [5]:
ref_index = []

for i in range(0,10):
    ref_index.append(S.tolist().index(list(reference[i])))

In [6]:
S

array([[2, 6, 9, ..., 3, 6, 5],
       [9, 3, 9, ..., 5, 7, 5],
       [4, 6, 2, ..., 1, 1, 1],
       ...,
       [4, 2, 7, ..., 4, 4, 9],
       [4, 7, 9, ..., 0, 8, 3],
       [9, 0, 9, ..., 7, 7, 4]])

In [7]:
reference

array([[0, 7, 5, 9, 5, 4, 3, 1, 9, 3, 7, 0, 6, 6, 8, 8, 8, 4, 6, 0],
       [9, 2, 9, 0, 2, 1, 5, 7, 7, 4, 9, 2, 0, 5, 8, 1, 2, 4, 5, 4],
       [3, 5, 0, 8, 0, 2, 5, 5, 9, 8, 1, 2, 1, 1, 6, 4, 9, 7, 9, 8],
       [4, 4, 7, 4, 9, 9, 1, 1, 0, 1, 2, 9, 3, 6, 9, 2, 4, 2, 4, 7],
       [2, 2, 9, 2, 2, 7, 0, 7, 5, 5, 9, 6, 6, 4, 1, 9, 9, 8, 7, 0],
       [6, 1, 3, 1, 4, 1, 7, 9, 3, 6, 5, 5, 7, 2, 9, 5, 1, 9, 6, 5],
       [3, 7, 8, 9, 1, 4, 6, 1, 2, 3, 7, 1, 5, 6, 9, 1, 0, 3, 2, 2],
       [2, 1, 5, 3, 4, 2, 2, 8, 9, 2, 4, 1, 2, 8, 0, 8, 3, 2, 5, 1],
       [7, 0, 2, 0, 8, 9, 9, 6, 1, 0, 9, 8, 6, 0, 2, 5, 6, 2, 2, 3],
       [6, 1, 3, 1, 6, 1, 6, 0, 7, 7, 9, 4, 6, 8, 1, 0, 5, 5, 6, 6]])

In [8]:
ref_index

[1827, 7184, 2509, 2019, 3473, 3588, 2399, 5145, 7166, 8087]

In [10]:
S[0] - reference[0]

array([ 2, -1,  4, -8,  4,  5, -1,  5, -8,  4,  1,  0, -3, -6, -8,  0, -4,
       -1,  0,  5])

In [18]:
np.sum(abs(S[0]-reference[2]))

84

In [34]:
distance2 = []
for i in S:
    for j in reference:
        
        distance2.append(np.sum(abs(i-j)))
        

In [35]:
distance2

[70,
 71,
 84,
 63,
 55,
 74,
 75,
 59,
 60,
 71,
 82,
 57,
 62,
 99,
 59,
 60,
 79,
 85,
 70,
 59,
 49,
 70,
 71,
 80,
 66,
 73,
 56,
 52,
 71,
 88,
 61,
 80,
 79,
 70,
 56,
 63,
 56,
 64,
 67,
 64,
 59,
 68,
 93,
 66,
 60,
 73,
 68,
 60,
 55,
 60,
 67,
 92,
 61,
 66,
 72,
 77,
 88,
 68,
 73,
 68,
 80,
 79,
 82,
 57,
 77,
 74,
 71,
 85,
 52,
 53,
 72,
 73,
 66,
 69,
 91,
 76,
 63,
 73,
 76,
 81,
 55,
 72,
 53,
 84,
 44,
 69,
 70,
 46,
 83,
 72,
 67,
 70,
 51,
 82,
 76,
 75,
 86,
 54,
 81,
 64,
 68,
 69,
 84,
 37,
 65,
 76,
 61,
 67,
 64,
 55,
 70,
 63,
 66,
 71,
 89,
 52,
 69,
 73,
 72,
 81,
 56,
 65,
 50,
 75,
 71,
 60,
 63,
 69,
 76,
 61,
 84,
 59,
 80,
 75,
 71,
 66,
 59,
 71,
 70,
 75,
 77,
 44,
 85,
 70,
 68,
 63,
 54,
 60,
 81,
 54,
 44,
 85,
 70,
 73,
 53,
 72,
 65,
 67,
 74,
 59,
 76,
 75,
 78,
 49,
 87,
 68,
 69,
 81,
 56,
 75,
 56,
 69,
 70,
 69,
 83,
 72,
 49,
 71,
 84,
 49,
 67,
 76,
 61,
 68,
 76,
 71,
 78,
 58,
 79,
 66,
 68,
 61,
 58,
 73,
 77,
 66,
 75,
 69,
 72,
 45,


In [56]:
dist_l = []
dist_l_filter = []
dist_filter = []

for i in S:
  for j in reference:
    
    dist_filter.append(np.sum(abs(i-j)))

    if len(dist_filter) == len(reference):
      dist_filter = np.array(dist_filter)
      filterd = np.argsort(dist_filter)[:2]
      dist_l_filter.extend(filterd)
      dist_filter = []
      dist_filter.clear()

In [57]:
dist_l_filter

[4,
 7,
 1,
 4,
 0,
 7,
 4,
 6,
 8,
 0,
 2,
 3,
 8,
 9,
 6,
 2,
 4,
 7,
 2,
 7,
 3,
 9,
 5,
 1,
 2,
 0,
 1,
 6,
 1,
 6,
 0,
 4,
 3,
 8,
 6,
 9,
 7,
 2,
 9,
 2,
 2,
 6,
 2,
 7,
 6,
 3,
 8,
 5,
 6,
 9,
 4,
 5,
 6,
 7,
 2,
 4,
 6,
 5,
 0,
 9,
 9,
 7,
 0,
 4,
 7,
 0,
 3,
 6,
 7,
 1,
 9,
 3,
 4,
 7,
 8,
 4,
 9,
 2,
 1,
 7,
 2,
 5,
 5,
 1,
 4,
 0,
 4,
 7,
 9,
 1,
 0,
 5,
 3,
 7,
 5,
 8,
 3,
 5,
 2,
 1,
 9,
 1,
 9,
 8,
 8,
 3,
 3,
 6,
 6,
 0,
 8,
 3,
 9,
 5,
 7,
 0,
 9,
 1,
 9,
 7,
 2,
 5,
 6,
 2,
 0,
 6,
 1,
 0,
 3,
 6,
 6,
 9,
 7,
 3,
 3,
 9,
 4,
 9,
 2,
 0,
 2,
 9,
 6,
 3,
 5,
 9,
 6,
 1,
 2,
 0,
 0,
 2,
 2,
 3,
 3,
 2,
 8,
 6,
 9,
 8,
 7,
 5,
 5,
 8,
 5,
 2,
 4,
 7,
 3,
 0,
 3,
 6,
 3,
 6,
 1,
 3,
 5,
 2,
 8,
 9,
 7,
 9,
 3,
 5,
 5,
 4,
 7,
 0,
 2,
 7,
 8,
 6,
 5,
 7,
 9,
 1,
 0,
 6,
 4,
 7,
 9,
 5,
 1,
 5,
 7,
 3,
 7,
 5,
 1,
 5,
 5,
 2,
 1,
 7,
 6,
 1,
 5,
 7,
 2,
 0,
 3,
 2,
 4,
 7,
 2,
 7,
 0,
 6,
 5,
 1,
 5,
 4,
 5,
 1,
 8,
 4,
 3,
 2,
 3,
 8,
 7,
 1,
 6,
 8,
 5,
 1,
 2,
 4,
 5,
 2,


In [41]:
distance[0:10], distance[10:20]

([70, 71, 84, 63, 55, 74, 75, 59, 60, 71],
 [82, 57, 62, 99, 59, 60, 79, 85, 70, 59])

In [43]:
dist_l_filter[0:10], dist_l_filter[10:20]

([4, 7, 8, 3, 0, 1, 9, 5, 6, 2], [1, 4, 9, 5, 2, 8, 6, 0, 7, 3])

In [58]:
len(dist_l_filter)

20000

In [59]:
pruned_ordered_list = np.reshape(np.asarray(dist_l_filter),(10000,2))
pruned_ordered_list

array([[4, 7],
       [1, 4],
       [0, 7],
       ...,
       [6, 3],
       [3, 8],
       [1, 5]], dtype=int64)

In [70]:
len(pruned_ordered_list)

10000

In [60]:
metric_dict = {}
o = 0
for i in pruned_ordered_list:
  o+=1
  for j in i:
    if j in metric_dict:
      metric_dict[j].append((o, i.tolist().index(j)))
    else:
      metric_dict[j] = []
      metric_dict[j].append((o, i.tolist().index(j)))

In [71]:
metric_dict[4]

[(1, 0),
 (2, 1),
 (4, 0),
 (9, 0),
 (16, 1),
 (26, 0),
 (28, 1),
 (32, 1),
 (37, 0),
 (38, 1),
 (43, 0),
 (44, 0),
 (69, 0),
 (84, 0),
 (93, 1),
 (100, 0),
 (112, 0),
 (116, 1),
 (118, 1),
 (124, 1),
 (136, 0),
 (143, 0),
 (145, 0),
 (172, 1),
 (179, 0),
 (186, 1),
 (200, 1),
 (205, 1),
 (207, 1),
 (212, 1),
 (221, 1),
 (241, 0),
 (243, 1),
 (254, 0),
 (260, 0),
 (270, 1),
 (305, 0),
 (309, 0),
 (310, 1),
 (332, 0),
 (338, 1),
 (346, 1),
 (347, 0),
 (356, 0),
 (358, 1),
 (363, 0),
 (370, 0),
 (379, 0),
 (384, 0),
 (391, 1),
 (392, 1),
 (393, 1),
 (400, 1),
 (408, 1),
 (411, 0),
 (421, 0),
 (430, 0),
 (465, 0),
 (473, 1),
 (481, 0),
 (490, 1),
 (492, 0),
 (512, 1),
 (523, 0),
 (536, 1),
 (540, 0),
 (543, 0),
 (564, 1),
 (567, 1),
 (568, 0),
 (571, 0),
 (586, 1),
 (597, 1),
 (603, 1),
 (606, 1),
 (613, 0),
 (615, 1),
 (619, 0),
 (620, 1),
 (625, 1),
 (628, 1),
 (631, 1),
 (640, 0),
 (643, 1),
 (660, 0),
 (674, 1),
 (679, 0),
 (682, 0),
 (685, 1),
 (686, 0),
 (698, 0),
 (701, 1),
 (708, 

In [61]:
len(metric_dict)

10

# Find the unique objects from the MIF_dict

In [62]:
type(metric_dict.values())

dict_values

In [63]:
mif_list = list(metric_dict.values())

In [64]:
flat_mif = [item for sublist in mif_list for item in sublist]

In [52]:
flat_mif[0:10]

[(1, 0),
 (2, 1),
 (3, 3),
 (4, 0),
 (5, 2),
 (6, 5),
 (7, 5),
 (8, 9),
 (9, 0),
 (10, 6)]

In [65]:
mif_index = []

for a,b in flat_mif:
    mif_index.append(a)

In [66]:
set_mif_index = set(mif_index)

In [67]:
len(set_mif_index)

10000

# This is my search portion

In [74]:
a = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

In [75]:
len(a)

20

In [94]:
def search_query(a):
    accumulator = []
    for i in S:
        accumulator.append(np.sum(abs(a-i)))
    accum_index = np.argsort(accumulator)[0:20]
    
    for i in accum_index:
               print(i, S[i])
    
    return

In [95]:
search_query(a)

8956 [2 0 0 1 0 6 4 7 1 0 3 5 1 1 2 1 0 0 3 1]
669 [0 2 4 2 8 2 3 2 2 0 2 0 1 2 0 4 2 3 1 2]
5077 [1 4 2 2 2 1 2 4 7 0 0 7 1 2 4 2 0 3 0 2]
5516 [4 1 0 5 0 3 3 7 2 3 6 2 2 1 0 2 1 1 0 4]
729 [3 1 5 0 0 1 1 6 1 0 6 3 0 4 2 7 1 0 0 6]
9467 [2 0 0 2 0 1 5 0 1 1 2 4 9 3 1 4 3 5 3 2]
2559 [2 4 7 3 7 3 1 0 0 3 0 1 3 2 1 3 2 3 3 0]
6773 [0 0 0 9 1 0 2 8 3 0 0 0 5 6 7 5 0 0 0 3]
1424 [0 3 3 5 3 4 2 0 3 2 8 0 4 2 2 1 3 0 0 4]
7724 [1 0 0 0 0 4 6 6 6 2 6 3 0 1 1 0 2 1 3 7]
1517 [1 1 4 0 5 3 7 2 1 5 2 2 0 2 1 1 0 7 3 2]
4347 [0 1 0 3 6 3 3 2 0 8 3 0 5 1 0 3 4 0 4 4]
9301 [0 6 0 2 9 4 1 0 4 0 2 7 7 0 0 0 5 0 2 1]
6075 [2 2 0 8 1 3 0 9 5 2 1 8 1 3 1 0 2 2 1 0]
3075 [0 0 6 5 2 2 0 3 1 0 7 3 2 0 1 4 5 1 2 8]
1577 [0 4 2 2 4 0 8 6 1 2 0 2 0 7 3 1 7 1 2 0]
7655 [0 4 7 1 7 1 0 2 1 1 4 9 4 1 1 0 1 0 5 3]
7 [9 8 0 3 1 1 1 0 0 4 1 0 3 1 6 5 6 1 1 2]
3145 [3 2 0 2 1 2 3 0 6 2 2 0 6 0 7 0 1 6 5 5]
595 [1 2 6 8 5 6 1 3 0 0 2 0 1 8 1 6 0 0 3 0]


In [96]:
search_query([9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9])

9389 [7 8 8 9 9 2 9 9 4 7 4 7 4 9 3 5 8 9 9 9]
2740 [7 3 8 7 5 8 8 0 9 8 9 5 6 9 4 8 9 6 8 8]
3709 [6 9 8 9 5 8 8 9 2 8 8 1 7 2 8 5 9 8 8 6]
2185 [5 9 9 9 9 8 9 4 9 9 4 1 5 8 8 6 8 5 6 3]
4791 [8 9 6 9 9 8 7 6 4 8 5 7 7 5 1 1 9 9 7 8]
6407 [9 5 9 4 7 9 9 9 7 3 6 6 6 8 6 0 8 6 6 8]
9553 [5 6 9 9 5 9 7 7 9 5 2 9 8 1 5 8 8 6 8 4]
3874 [8 3 9 4 9 9 9 8 6 4 4 2 8 7 8 7 8 5 8 4]
4081 [8 8 5 6 5 2 5 4 9 8 9 9 3 5 8 8 6 8 7 6]
2155 [6 7 5 2 1 9 6 7 6 8 9 9 8 5 8 3 8 6 9 7]
468 [6 7 4 3 7 2 9 6 9 7 9 9 3 9 9 8 4 6 6 6]
2356 [4 8 4 5 9 3 8 9 7 9 6 8 6 7 6 8 4 8 5 5]
5429 [9 4 3 6 9 5 9 8 3 7 9 9 8 6 5 4 8 4 8 5]
6721 [6 9 3 5 9 8 9 2 8 8 7 1 3 9 7 8 9 4 7 7]
996 [6 9 8 6 6 5 1 5 9 4 7 8 6 9 9 4 7 9 8 3]
217 [1 8 9 3 6 6 8 2 2 8 8 9 9 6 9 9 4 8 5 8]
3229 [9 6 6 8 9 8 7 6 4 9 3 6 8 3 2 8 6 9 9 2]
2949 [7 0 7 9 9 4 9 9 2 8 7 1 9 9 2 7 9 9 4 7]
1819 [5 9 9 8 6 0 8 6 6 4 0 8 4 9 8 8 9 9 2 9]
6466 [7 2 5 6 9 5 7 8 9 8 4 8 8 4 4 8 9 9 4 3]


In [97]:
search_query([1,2,3,4,5,9,9,9,9,2,3,4,5,6,9,2,9,9,9,9])

3983 [2 9 1 3 5 9 7 9 8 3 6 4 5 6 4 6 3 8 9 9]
1471 [3 1 4 9 3 6 8 7 9 0 2 7 7 5 6 2 8 9 9 3]
5084 [0 6 2 4 2 7 9 7 9 0 4 4 4 9 6 2 8 7 1 5]
3009 [1 2 5 6 6 6 9 6 5 0 1 3 4 9 6 5 9 6 8 3]
8174 [2 2 4 5 6 8 8 8 9 5 4 6 8 2 0 3 9 3 8 6]
1595 [8 4 0 9 5 8 8 9 8 1 0 2 5 8 9 9 6 8 9 8]
4236 [1 6 3 8 9 6 9 9 6 0 3 1 6 6 4 4 7 4 7 9]
779 [2 5 5 0 3 7 8 8 9 3 3 8 3 9 3 4 5 9 7 8]
5569 [2 0 5 0 8 6 6 7 3 5 2 4 7 4 8 2 8 9 6 7]
6552 [0 6 1 2 7 6 8 9 9 9 6 5 6 7 0 5 8 9 9 8]
995 [7 4 3 4 0 9 3 9 7 1 3 1 7 7 2 2 8 8 8 5]
6807 [6 0 2 3 0 6 9 6 8 3 7 0 1 8 7 3 8 8 8 9]
9689 [4 1 5 5 5 6 9 7 8 1 6 2 3 3 5 9 9 9 9 2]
4304 [2 7 5 5 5 7 6 8 7 0 4 1 6 7 9 1 6 1 7 6]
9571 [2 3 2 6 9 5 4 9 9 0 2 0 9 5 9 8 9 8 3 9]
2149 [0 0 3 6 7 5 4 9 4 7 7 4 1 7 8 1 8 8 6 8]
2061 [0 3 2 1 6 4 9 4 6 0 1 3 5 1 7 0 9 8 4 6]
101 [5 7 1 1 0 9 5 9 9 3 4 4 5 9 8 2 3 5 5 9]
9854 [1 3 8 6 6 5 4 8 6 3 6 4 1 5 9 8 9 9 3 9]
4626 [4 3 0 1 6 6 9 8 3 2 6 6 3 9 8 3 3 8 9 6]
